import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { ProductModalProvider } from "@/providers/product-modal-provider";
import localFont from "next/font/local";
// 2. Configure the font
const beatrice = localFont({
  src: [
    {
      path: "../public/fonts/BeatriceDeckTrialLight.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/BeatriceDeckTrialMedium.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/BeatriceDeckTrialExtrabold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-beatrice", // 3. Define a CSS variable name
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${beatrice.variable} antialiased font-beatrice `}>
        <ProductModalProvider>
          <Navbar />
          {children}
        </ProductModalProvider>
      </body>
    </html>
  );
}
